#
# FIXME rustc "runs" without error, but there's a problem:
#       it generates an .exe file, but there's no output.
#

[package]
name = "hello-jj"
version = "0.1.0"
edition = "2024"

[dependencies]
